
<html>
<head>
<title></title>
</head>
<body bgcolor="yellow">

      <center><h1>Welcome</h1></center>
       <div align="center"><img src="img/vote.jpg" alt="Online college E-voting" width="200" height="210" /> </div>
       <div align="center"><h1>About Online E-voting System</h1> </div>
       <p align="left">
       <center>
       <h3>
        Online voting is the electronic voting(e-voting). This web application provides   facilities to conduct online voting at acadmic level.<br>It saves time as it allows number of students to give votes to the candidates and displays the result as the online voting.<br>It is automatically generated by the server. User can register login and give the vote with his provided ID.<br>Online voting is the inovative technology to partial justification and  we can use online voting  for avoiding the duplications of votes,and is the protective way for voting.
	</h3>
	</center>
	</p>
        <ul type="disc">
          <li><h3> Advantage of the online voting system :</h3></li>
        <ol type="1">
		<li> Time saving</li>
		<li> Working load reduced to a large extent</li>
		<li> Less prone to errors</li>
		<li>Information available at time</li>
		<li>Man power reduced</li>
		<li>Many tasks are automated</li>
		<li>It also provide security for the data</li>
	</ol>
          <li><h3> Future scope: </h3></li>
          <p>
	The future scope for  this software is very dynamic. Next stage may be implementated depening on the time factor.</p>
	<p>The main advantages of this projects are:</p>
	<ol type="1">
		<li>	It provides easy information about procedure of online voting system.</li>
		<li>	It provides well structured information.</li>
		<li>	It makes free from manual work.</li>
		<li>	Any information needed can be obtained by any time by queries.</li>
	</ol>
        </ul>      

	<a href="index.php" align="center" ><h2> Back</h2>  </a>
</body>
</html>
